// Code generated by sysl DO NOT EDIT.
package simple

import (
	"context"
)

// DefaultSimpleImpl  ...
type DefaultSimpleImpl struct {
}

// NewDefaultSimpleImpl for Simple
func NewDefaultSimpleImpl() *DefaultSimpleImpl {
	return &DefaultSimpleImpl{}
}

// GetFoobarList Client
type GetFoobarListClient struct {
}

// GetStuffList Client
type GetStuffListClient struct {
}

// ServiceInterface for Simple
type ServiceInterface struct {
	GetFoobarList func(ctx context.Context, req *GetFoobarListRequest, client GetFoobarListClient) (*Foo, error)
	GetStuffList  func(ctx context.Context, req *GetStuffListRequest, client GetStuffListClient) (*Stuff, error)
}
