// Code generated by sysl DO NOT EDIT.
 package simple 
 
 import (
 "context" 
 "fmt" 
 "net/http" 
 "net/url" 
 "github.service.anz/sysl/server-lib/restlib" 
 "github.service.anz/sysl/server-lib/common" 
 
)
 
 // Service interface for Simple 
 type Service interface {
 	 GetStuffList ( ctx context.Context , req *GetStuffListRequest ) ( *Stuff, error ) 
 }

 // Client for Simple API 
 type Client struct {
 	 client *http.Client 
 	 url string 
 }

 // NewClient for Simple 
 func NewClient ( client *http.Client , serviceURL string ) *Client {
 	 return &Client{client, serviceURL} 
 }
 

 // GetStuffList ... 
 func ( s *Client ) GetStuffList ( ctx context.Context , req *GetStuffListRequest ) ( *Stuff, error ) {
 	 required := [] string {  } 
 	 okResponse := &Stuff{} 
 	 u, err := url.Parse ( fmt.Sprintf ( "%s/stuff" , s . url ) ) 
 	 if err != nil {
 	 return nil, common.CreateError(ctx, common.InternalError, "failed to parse url", err) 
 }
 
 	 result, err := restlib.DoHTTPRequest ( ctx , s . client , "GET" , u.String ( ) , nil , required , okResponse , nil ) 
 	 if err != nil {
 	 return nil, common.CreateError(ctx, common.DownstreamUnavailableError, "call failed: Simple <- GET " + u.String(), err) 
 }
 
 	 if result.HTTPResponse.StatusCode == http.StatusUnauthorized {
 	 return nil, common.CreateDownstreamError(ctx, common.DownstreamUnauthorizedError, result.HTTPResponse, result.Body, nil) 
 }
 
 	 OkStuffResponse, ok := result.Response.(*Stuff) 
 	 if ok {
 	 valErr := validator.Validate ( OkStuffResponse ) 
 	 if valErr != nil {
 	 return nil, common.CreateDownstreamError(ctx, common.DownstreamUnexpectedResponseError, result.HTTPResponse, result.Body, valErr) 
 }
 
 	 return OkStuffResponse, nil 
 }
 
 	 return nil, common.CreateDownstreamError(ctx, common.DownstreamUnexpectedResponseError, result.HTTPResponse, result.Body, nil) 
 }
 

 
 