// Code generated by sysl DO NOT EDIT.
package simple

import (
	"time"

	"github.com/rickb777/date"
	"github.service.anz/sysl/server-lib/common"
	"github.service.anz/sysl/server-lib/validator"
)

// Reference imports to suppress unused errors
var _ = time.Parse

// Reference imports to suppress unused errors
var _ = date.Parse

// Stuff ...
type Stuff struct {
	InnerStuff     string                 `json:"innerStuff"`
	SensitiveStuff common.SensitiveString `json:"sensitiveStuff"`
}

// GetStuffListRequest ...
type GetStuffListRequest struct {
}

// *Stuff validator
func (s *Stuff) Validate() error {
	return validator.Validate(s)
}
